- hosts: mihost
  vars:
    servercode: SX132
    username: manu
  tasks:
  - name: Upload config file for installimage
    template: 
      src='hetzner_configs/config-{{ servercode }}.j2'
      dest='/root/config-{{ servercode }}'
  - name: Launching installimage
    shell: "/root/.oldroot/nfs/install/installimage -c /root/config-{{ servercode }} -a"
  - name: Server reboot
    reboot:
      reboot_timeout: 3600
  - name: Bootstrap a host without python2 installed
    raw: "apt-get update && apt-get -y install python"
  - name: "Create group {{ username }}"
    group:
      name: "{{ username }}"
      state: present
  - name: "Create user {{ username }} on server"
    user:
    # echo -n "ultraSecurePassword" | mkpasswd --method=sha-512 -s
        name: "{{ username }}"
        group: "{{ username }}"
        groups: sudo
        password: "$[MY_SECURE_PASS]"
        shell: /bin/bash
        append: yes
        update_password: on_create
        state: present
  - name: Gather facts manually
    setup:
      gather_subset:
        - all
  - name: Install basic packages
    apt: state=present pkg={{ item }} update_cache=yes
    with_items:
      - lsb-core
      - apt-transport-https
      - sudo
      - python-pip
      - vim
      - screen
      - htop
      - tmux
      - git
      - zsh
      - telnet
      - ftp
      - netcat
      - source-highlight
      - xclip
      - xauth
      - p7zip-full
      - unrar
      - wget
      - curl
      - rsync
      - htop
      - iotop
      - strace
      - ltrace
      - whois
      - screen
      - iperf
      - ntpdate
      - ufw
      - openvpn
      - unzip
      - iptables-persistent
      - python-virtualenv
      - virtualenv
      - virtualenvwrapper
      - keychain
      - smartmontools
      - socat
  - name: Configure locales
    locale_gen:
      name: "{{ item }}"
      state: present
    with_items:
      - en_US.UTF-8
      - es_ES.UTF-8
  - name: Updating system locales
    raw: locale-gen
  - name: Set timezone to Europe/Madrid
    timezone:
      name: Europe/Madrid
  - name: Updating date and time
    shell: "ntpdate -u pool.ntp.org"
